In [3]:
from sklearn.cluster import KMeans
import numpy as np

# Exemplo de dados de usuários, onde cada linha representa um usuário
# e cada coluna representa uma característica de preferência
data = np.array([
    [5.0, 3.0, 0, 0],
    [4.0, 0, 4.5, 3.5],
    [0, 5.0, 4.0, 4.5],
    [0, 3.5, 4.0, 0]
])

# Configurando o KMeans com um número desejado de clusters
kmeans = KMeans(n_clusters=2, random_state=0)

# Ajustando o modelo aos dados
kmeans.fit(data)

# Saída dos centróides dos clusters e das etiquetas de cada ponto
print("Centroids:")
print(kmeans.cluster_centers_)
print("Labels:")
print(kmeans.labels_)

# Prever o cluster para um novo conjunto de dados
new_data = np.array([
    [0, 4.0, 3.0, 3.0],
    [5.0, 3.5, 0, 0]
])
print("New Data Labels:")
print(kmeans.predict(new_data))

Centroids:
[[0.   4.25 4.   2.25]
 [4.5  1.5  2.25 1.75]]
Labels:
[1 1 0 0]
New Data Labels:
[0 1]
